[package]
name = "rubsty"
version = "0.1.0"
authors = ["Frederik Wille <frederik@wille.hamburg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
itertools = "0.10.0"
comfy-table = "1.5.0"
strum = "0.20.0"
strum_macros = "0.20"
clap = "3.0.0-beta.2"
